// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvK3urstpsL8o1aq_d2g7cYjqGAf3_ZI',
    appId: '1:301089465058:web:7228f6cf3c23310909f4bb',
    messagingSenderId: '301089465058',
    projectId: 'apesapp-60ee8',
    authDomain: 'apesapp-60ee8.firebaseapp.com',
    storageBucket: 'apesapp-60ee8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WtMFHWiRJYFctlUIOj87iXOQp-NgsWA',
    appId: '1:301089465058:android:b8e6df36246e569c09f4bb',
    messagingSenderId: '301089465058',
    projectId: 'apesapp-60ee8',
    storageBucket: 'apesapp-60ee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLZyk_f-tVSbs29npPHHEViUSR--vdVA',
    appId: '1:301089465058:ios:6f4e3bc32be7295409f4bb',
    messagingSenderId: '301089465058',
    projectId: 'apesapp-60ee8',
    storageBucket: 'apesapp-60ee8.firebasestorage.app',
    androidClientId: '301089465058-o9n8nu4dea8kfsb7614vsb209b98n0f9.apps.googleusercontent.com',
    iosClientId: '301089465058-3lul1a4fmnq268n50hs4pm9i7b1k59m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:3be076689b6866ea0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-qfcmju8p2mbqre4rl5kufhr7dhs9hs33.apps.googleusercontent.com',
    iosClientId: '823307041176-7pen3ehk09mbnp7ukg6lm4a9sgr80pjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}